### ISSUE TITLE
Sidebar Issues

### ISSUE THREAD

**Issue by Musecman** [dflippo/UU2014#34]
I accidentally hid the Sidebar Widget area just to see what it would look like without it, in the Theme - Customize - Display/Hide Feature. I want to add it back and it won't add back. I've uninstalled, and re-installed. and still won't go back

**Comment by sLynetta** [comment]
I have the same problem. I absolutely love this theme, but 
 -  I can't get any sidebars or widgets or any jetpack features to show up at all. 
 -  I've uninstalled and resinstalled as well. 
 -  All theme settings are marked to SHOW. 
 -  I'm signed into jetpack. All Jetpack plugins are current. 
 -  Everything is current in the theme itself, the most recent version. 

I really don't want to look for another theme. I love yours so please ehlp.

**Comment by dflippo** [comment]
The sidebars are designed to display only when 1) the setting in Customizer is set to Display and 2) there is at least one widget in the sidebar.  My first guess is that you don't have a widget in the intended sidebar.  I suggest you create a text widget with unique text ("region 1" , 2, etc) for each of the six different widget areas to see if they work some places but not others.

also, there is a very good chance that the very new release that just went live at 11 pm EST fixes the issue.  You should make sure that all your Customizer text field settings aren't empty.  WordPress introduced new features for the Customizer in WP 4.1 and the screens weren't working right before for some settings.  If you have any blank settings and need to know the default value, let me know which field and I can let you know what to enter.  For settings other than text fields, you just need to make sure all the settings are now what you want.  You are going to see that I added several new sections to the Customizer related to font sizes.  If necessary, I am willing to setup a time for a Google Hangout to diagnose this issue with either of your sites.  I am sorry if the last release caused this issue for you.  I fixed several issues early last week but it took longer than usual for WP to review/approve the release due to the holiday.

**Comment by sLynetta** [comment]
I did those things. I did notice that things have changed in the last couple of hours. I'll check back again. Thanks for all you do. L

**Comment by dflippo** [comment]
No problem.  The more I think about it, I believe the issue you found was isolated to version 1.3.5 and fixed in 1.3.6.  WP 4.1 required me to specify a function to "sanitize" each Customizer setting and samples online said I could use the "is_int" method but I learned that doesn't work.  I added my own sanitize function for the Display/Hide settings in 1.3.6.  I think it was the root cause of your issues.

**Comment by Musecman** [comment]
![1](https://cloud.githubusercontent.com/assets/10382022/5604887/63f397a2-93a9-11e4-914a-ad0735788134.png)
![2](https://cloud.githubusercontent.com/assets/10382022/5604888/65fafd06-93a9-11e4-8f14-6696b056313d.png)

Still not fixed....I have wordpress 4.1

**Comment by dflippo** [comment]
Could you try changing all the settings to hide, save, change all to display, and save again?  The sanitize function hits when you save and cycling through the settings might fix the issue.

**Comment by Musecman** [comment]
I did that....didn't work.....this is what i get every time i go back to customize...no buttons are clicked

![problem](https://cloud.githubusercontent.com/assets/10382022/5604897/99c8f9d4-93aa-11e4-8a9f-74cf98c5cc7c.png)

**Comment by dflippo** [comment]
Darn, that is what I saw when I discovered the issue with is_int.  I suggest deleting and adding the theme back to make 100% sure you are on 1.3.6.  I should also warn you that unrelated to the theme that sometimes the preview doesn't reflect all your changes (better to save and then view outside the Customizer) but that is not what I think is happening.  The reason that deleting and adding it back didn't fix the issue when you have tried that is that the theme settings are not deleted when the theme is deleted.  In your case we might need to delete the saved settings to get you back at a good starting point.  It is getting late but I will research first thing tomorrow on resetting all the theme settings to default.  Thanks for getting back to me and working with me on the issue.  I am thinking that it would be a good feature to have a "reset all theme settings to default" button to help anyone with a similar issue in the future.  I can give you a zip tomorrow with a test version if that is OK with you.

**Comment by Musecman** [comment]
hmmm....I uninstalled and went through my WP gateway to download the theme again...and it worked....So no more issues with that...thank you very very much....You have an awesome theme that is everything i need.....i'm going to go find a place where your theme is submitted and give you a great review for the support and theme itself!

also if you want to send me that test version to try it out...i'm up for it....that's an excellent idea to have that reset

**Comment by Musecman** [comment]
![review](https://cloud.githubusercontent.com/assets/10382022/5604957/c88975e6-93af-11e4-89c8-3fed1d4c7e34.png)

**Comment by dflippo** [comment]
I just committed the change for the reset button to Git.  You have a few options to test, you can replace your /inc/customizer.php file with the version here:
https://raw.githubusercontent.com/dflippo/UU2014/master/inc/customizer.php

Or, you can delete the version of the theme you have and install this zip:
https://github.com/dflippo/UU2014/archive/master.zip

Unfortunately, although this zip will work fine in WordPress, it will break your upgrade ability in WordPress unless you rename the "UU2014" folder GitHub puts in there to "uu-2014" which is what WordPress.org puts in their zip.

There is also the option to leave the UU2014 folder alone and install the GitHub Updater plugin.  The theme supports that plugin and it allows you to update directly to the "master" version.

I have some different changes to improve menus for mobile devices that I am going to add before submitting this next release to WordPress.  I have those nearly complete and will probably submit later today or tomorrow.

**Comment by Musecman** [comment]
A little help here...how do i get rid of this? I don't want people to have access to my Admin login page....

![untitled-1](https://cloud.githubusercontent.com/assets/10382022/5609776/0e3b634e-9476-11e4-8ac5-498ea22ad2da.png)

**Comment by dflippo** [comment]
That is there intentionally.  The primary use of the theme is by
UU churches and adding the login link to the bottom of every page has
proven overall to be a big help for less technical users.  Users still have
to login before getting to the back-end.

The best approach to removing it is to create a child theme.  When you
create a child theme you have the option to create your own custom version
of some of the files in the theme.  It is the best approach because direct
changes to the theme will be lost when you apply any updates to the theme.
You can also replace any of the image files in your child theme and the
theme will then use your version.  The login link is contained in the
footer.php template and I don't think you will have much trouble taking it
out.  There are many tutorials online for creating a child theme but let me
know if you have trouble.  Prior to this theme there was a UU2011 theme by
a different author and I had my own child theme to apply some of the
changes that are now in UU2014.  You should only need to have a
functions.php, style.css, and footer.php file to make this change.  By
leaving the other php files out, it will revert to using the parent theme's
files.  The tutorials should explain the changes you need to make in the
style.css and functions.php files to let Wordpress know that your files are
a child theme.  I believe there are also plugins that automate the process
of creating a child theme but I can't say that I have tried any of them.

Dan

On Monday, January 5, 2015, Musecman <notifications@github.com> wrote:

> A little help here...how do i get rid of this? I don't want people to have
> access to my Admin login page....
>
> [image: untitled-1]
> <https://cloud.githubusercontent.com/assets/10382022/5609776/0e3b634e-9476-11e4-8ac5-498ea22ad2da.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dflippo/UU2014/issues/34#issuecomment-68671275>.
>


-- 
Dan Flippo
Mobile - (330) 990-4811
Personal email - djf13@cornell.edu

**Comment by dflippo** [comment]
Just to follow up on this issue, Version 1.3.8 was released yesterday on WordPress.org and I think all the issues in the customizer are now fixed.  It was the validation function and it took a couple releases to figure out exactly what was causing it to sometimes misbehave.  This version also includes the reset feature.  Thanks for the generous comment over on the WordPress site.

**Comment by hbmacp** [comment]
I have been working on our new website using the UU 2014 theme but cannot get the Primary Sidebar to display anything but a Sidebar menu that I developed (by specifying in the Navigation customization area that it should be used in the Secondary Menu) or a list of all our pages (which results if I do not specify a menu for the Secondary Menu area in the Navigation customization area).  
When I select Customize and then Widgets, I am shown only the Header, Footer and Content Header Widget areas to customize.  However, if I select Widgets directly from Appearance I get a full list of the various widget areas including the Primary Sidebar.  No matter what widgets I include in the Primary Sidebar area, it has absolutely no effect on what is actually displayed in the sidebar.  What am I not doing right to get widgets to display in the Primary Sidebar area?

**Comment by hbmacp** [comment]
I also can't get anything to show in the Content Footer Widget Area but can get something to show in the Content Header Widget Area.  There is no control in the Display and Hide Features customization for showing or hiding either of these two widget areas so it is not a problem with me having indicated "hide" for the Content Footer Widget Area.
